---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
    db_host: "localhost"
    new_db_host: "localhost"
  tasks:
    - name: "This is name"
      set_fact:
        one_fact: "12345"
        other_fact: false
    - debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

    - name: "NEXT ONE..."
      debug:
        msg: "System {{ one_fact }} has uuid {{ other_fact }}"
    - debug:
        var: one_fact

    - name: "Announcement variables."
      set_fact:
        hostname: "{{db_host}}"
        db_port: 3306

    - name: "Comparing variables."
      set_fact:
        when: hostname == "localhost"
        hostname: "{{db_host}}3"
        db_port: "{{http_port}}"
    - debug:
        msg: "Hostname: {{hostname}} database port: {{ db_port }}"

    - name: "Run script."
      shell: "./test.sh {{hostname}}"
      when: hostname == "localhost2"
